# Generated by Django 5.2.8 on 2025-11-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rename_condition_asset_asset_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('printer', 'Printer'), ('projector', 'Projector'), ('furniture', 'Furniture')], default='desktop', max_length=50),
        ),
        migrations.DeleteModel(
            name='AssetCategory',
        ),
    ]
