# Generated by Django 5.2.8 on 2025-11-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_category_delete_assetcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('printer', 'Printer'), ('projector', 'Projector'), ('furniture', 'Furniture')], default='laptop', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='specification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
