# Generated by Django 5.2.8 on 2025-11-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_asset_category_alter_asset_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='category',
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('printer', 'Printer'), ('projector', 'Projector'), ('furniture', 'Furniture')], default='laptop', max_length=50),
        ),
    ]
