# Generated by Django 5.2.8 on 2025-11-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_remove_asset_category_alter_asset_asset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('maintenance', 'Maintenance'), ('retired', 'Retired'), ('returned', 'Returned')], default='available', max_length=20),
        ),
    ]
