# Generated by Django 5.2.8 on 2025-11-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_asset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_condition',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('printer', 'Printer'), ('projector', 'Projector')], default='laptop', max_length=50),
        ),
    ]
