# Generated by Django 5.2.8 on 2025-12-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_asset_asset_condition_alter_asset_asset_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='purchase_date',
        ),
    ]
