# Generated by Django 5.2.8 on 2025-12-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_remove_asset_purchase_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_name',
            new_name='asset_category',
        ),
    ]
