# Generated by Django 5.2.8 on 2025-12-02 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
