# Generated by Django 5.2.8 on 2025-11-07 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_remove_asset_category_alter_asset_asset_name'),
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetreturn',
            options={'ordering': ['-returned_date'], 'verbose_name': 'Asset Return', 'verbose_name_plural': 'Asset Returns'},
        ),
        migrations.AlterField(
            model_name='assetreturn',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateField(help_text='Expected return date')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Staff member who approved this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_asset_requests', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(help_text='The asset being requested', on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to='assets.asset')),
                ('user', models.ForeignKey(help_text='User who requested the asset', on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Request',
                'verbose_name_plural': 'Asset Requests',
                'ordering': ['-request_date'],
            },
        ),
        migrations.AlterField(
            model_name='assetreturn',
            name='borrow_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='requests.assetrequest'),
        ),
        migrations.DeleteModel(
            name='BorrowRequest',
        ),
    ]
