# Generated by Django 5.2.8 on 2025-11-08 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_asset_status'),
        ('requests', '0002_alter_assetreturn_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='assetreturn',
            options={'ordering': ['-returned_date']},
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_asset_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='request_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='return_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
