# Generated by Django 5.2.8 on 2025-12-02 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_asset_asset_condition_alter_asset_asset_name'),
        ('requests', '0005_alter_assetrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetrequest',
            options={'ordering': ['-request_date']},
        ),
        migrations.RemoveField(
            model_name='assetrequest',
            name='asset',
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='asset_category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('projector', 'Projector'), ('desktop', 'Desktop')], default='laptop', max_length=50),
        ),
        migrations.AddField(
            model_name='assetrequest',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='assetreturn',
            name='condition_on_return',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='good', max_length=10),
        ),
    ]
