# Generated by Django 5.2.8 on 2025-12-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_alter_assetrequest_options_remove_assetrequest_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetreturn',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
