# Generated by Django 5.2.8 on 2025-12-29 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_assetrequest_created_at_assetrequest_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='request_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
