# Generated by Django 5.2.8 on 2025-12-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_alter_assetrequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='asset_category',
            field=models.CharField(choices=[('laptop', 'Laptop'), ('projector', 'Projector'), ('desktop', 'Desktop')], max_length=50),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
