# Generated by Django 5.2.8 on 2025-12-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_alter_assetrequest_asset_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetreturn',
            name='returned_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
