# Generated by Django 5.2.8 on 2025-12-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0014_alter_assetreturn_returned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetreturn',
            name='returned_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
