# Generated by Django 5.2.8 on 2025-11-06 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('repair', 'Repair'), ('service', 'Service'), ('upgrade', 'Upgrade')], default='service', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('maintenance_date', models.DateField()),
                ('performed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
        ),
    ]
